# -*- coding: utf-8 -*-
"""automate_OryzaSativa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naIpR_Qtypf6r0ocMVDE3UYHCKm2-qua
"""

import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.decomposition import PCA

from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import IterativeImputer


def preprocess_data(
    input_path: str,
    train_output_path: str,
    test_output_path: str
):
    df = pd.read_csv(input_path)
    df = df.drop(columns=["id", "dataset", "ca", "thal"])

    num_cols = df.select_dtypes(include=["int64", "float64"]).columns
    imputer = IterativeImputer(random_state=42)
    df[num_cols] = imputer.fit_transform(df[num_cols])

    categorical_cols = ["sex", "cp", "fbs", "restecg", "exang", "slope"]
    for col in categorical_cols:
        df[col] = df[col].fillna(df[col].mode()[0]).infer_objects(copy=False)

    df["num"] = df["num"].apply(lambda x: 0 if x == 0 else 1)

    X = df.drop(columns=["num"])
    y = df["num"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    numerical_cols = ["age", "trestbps", "chol", "oldpeak"]
    categorical_cols = ["sex", "cp", "fbs", "restecg", "exang", "slope"]

    for col in numerical_cols:
        scaler = MinMaxScaler()
        X_train[col] = scaler.fit_transform(X_train[[col]])
        X_test[col] = scaler.transform(X_test[[col]])

    for col in categorical_cols:
        encoder = LabelEncoder()
        X_train[col] = encoder.fit_transform(X_train[col])
        X_test[col] = encoder.transform(X_test[col])

    pca = PCA(n_components=0.95, random_state=42)
    pca.fit(X_train[numerical_cols])

    X_train_pca = pca.transform(X_train[numerical_cols])
    X_test_pca = pca.transform(X_test[numerical_cols])

    pca_cols = [f"pca_{i+1}" for i in range(pca.n_components_)]

    X_train_pca = pd.DataFrame(X_train_pca, columns=pca_cols, index=X_train.index)
    X_test_pca = pd.DataFrame(X_test_pca, columns=pca_cols, index=X_test.index)

    X_train_final = pd.concat(
        [X_train.drop(columns=numerical_cols), X_train_pca],
        axis=1
    )

    X_test_final = pd.concat(
        [X_test.drop(columns=numerical_cols), X_test_pca],
        axis=1
    )

    train_clean = pd.concat([X_train_final, y_train], axis=1)
    test_clean = pd.concat([X_test_final, y_test], axis=1)

    train_clean.to_csv(train_output_path, index=False)
    test_clean.to_csv(test_output_path, index=False)


if __name__ == "__main__":
    preprocess_data(
        input_path="heart_disease_uci.csv",
        train_output_path="train_preprocessing.csv",
        test_output_path="test_preprocessing.csv"
    )